name: publishment
on:
    workflow_dispatch:
    pull_request_target:
        types:
            - closed
        branches:
            - main
        paths:
            - "src/**"
            - "README.md"
            - "package.json"
jobs:
    publish:
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true) }}
        runs-on: ubuntu-latest
        environment: ABYSSERS_PUBLISH_ENV
        steps:
            - name: "[Download Repo]"
              uses: actions/checkout@v2
              with:
                  ref: main
            - name: "[Setup NodeJs]"
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: "[Install Dependencies]"
              run: sudo npm install --unsafe-perm=true --allow-root --ignore-scripts
            - name: "[Build]"
              run: npm run build
            - name: "[Publish 2 NPM]"
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.MORILENCE_NPM_TOKEN }}
                  access: public
                  check-version: true
                  tag: beta
